package enum

// Category it's map
var Category = map[string]int{
	"archeologia":                101,
	"filozofia":                  102,
	"historia":                   103,
	"językoznawstwo":             104,
	"literaturoznawstwo":         105,
	"nauki o kulturze i religii": 106,
	"nauki o sztuce":             107,
	"architektura i urbanistyka": 201,
	"automatyka, elektronika i elektrotechnika":                 202,
	"informatyka techniczna i telekomunikacja":                  203,
	"inżynieria biomedyczna":                                    204,
	"inżynieria chemiczna":                                      205,
	"inżynieria lądowa i transport":                             206,
	"inżynieria materiałowa":                                    207,
	"inżynieria mechaniczna":                                    208,
	"inżynieria środowiska, górnictwo i energetyka":             209,
	"nauki farmaceutyczne":                                      301,
	"nauki medyczne":                                            302,
	"nauki o kulturze fizycznej":                                303,
	"nauki o zdrowiu":                                           304,
	"nauki leśne":                                               401,
	"rolnictwo i ogrodnictwo":                                   402,
	"technologia żywności i żywienia":                           403,
	"weterynaria":                                               404,
	"zootechnika i rybactwo":                                    405,
	"ekonomia i finanse":                                        501,
	"geografia społeczno-ekonomiczna i gospodarka przestrzenna": 502,
	"nauki o bezpieczeństwie":                                   503,
	"nauki o komunikacji społecznej i mediach":                  504,
	"nauki o polityce i administracji":                          505,
	"nauki o zarządzaniu i jakości":                             506,
	"nauki prawne":                                              507,
	"nauki socjologiczne":                                       508,
	"pedagogika":                                                509,
	"prawo kanoniczne":                                          510,
	"psychologia":                                               511,
	"astronomia":                                                601,
	"informatyka":                                               602,
	"matematyka":                                                603,
	"nauki biologiczne":                                         604,
	"nauki chemiczne":                                           605,
	"nauki fizyczne":                                            606,
	"nauki o Ziemi i środowisku":                                607,
	"nauki teologiczne":                                         701,
}
